config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'projects#index'
  resources :projects
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks
  validates :name, :summary, :start_date, :end_date, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
  belongs_to :user
  validates :title, :description, :status, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :tasks
  validates :first_name, :last_name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Токен безопасности для защиты от подделанных запросов
  protect_from_forgery with: :exception
  add_flash_types :success, :danger, :info, :warning
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_project, only: [ :show, :edit, :update, :destroy ]

  def index
    @projects = Project.all
  end

  def show; end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project, success: 'The project is successfully created'
    else
      render :new, danger: 'The project isn\'t created'
    end
  end

  def edit; end

  def update
    if @project.update_attributes(project_params)
      redirect_to @project, success: 'The project is successfully updated'
    else
      render :edit, danger: 'The project isn\'t updated'
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path, success: 'The project is successfully deleted'
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    #для фильтрации параметров
    # в параметрах обязательно должен присутствовать один из параметров projects, в котором разрешены след поля
    params.require(:project).permit(:name, :summary, :start_date, :end_date)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_task, only: [ :show, :edit, :update, :destroy ]

  def index
    @tasks = Task.all
  end

  def show; end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to @task, success: 'The task is successfully created'
    else
      render :new, danger: 'The task isn\'t created'
    end
  end

  def edit; end

  def update
    if @task.update_attributes(task_params)
      redirect_to @task, success: 'The task is successfully updated'
    else
      render :edit, danger: 'The task isn\'t updated'
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, success: 'The task is successfully deleted'
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :status, :project_id, :user_id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(name)
    {
        success: "alert-success",
        error: "alert-danger",
        danger: "alert-danger",
        alert: "alert-warning",
        notice: "alert-info",
    }[name.to_sym] || name # если метод не найден вернем имя
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Manager</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="container">
  <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="<%= projects_path %>">Projects</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%= tasks_path %>">Tasks</a>
      </li>
    </ul>

    <ul class="navbar-nav pull-xs-right">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        </li>
      <% else %>
      <li class="nav-item">
        <%= link_to 'Log in', new_user_session_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
      </li>
      <% end %>
    </ul>

  </nav>
</div>


<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% flash.each do |name, message| %>
        <!--div class="alert alert-<!%= bootstrap_class_for(name) %>"-->
        <div class="alert alert-<%= name %>">
          <button class="close" data-dismiss="alert">&times;</button>
          <%= message %>
        </div>
      <% end %>
    </div>
  </div>
  <%= yield %>
</div>
</body>
</html>

app/views/projects/_form.html.erb
<% if @project.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
  </div>
  <ul>
    <% @project.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @project do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :summary %>
    <%= form.text_area :summary, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :start_date %>
    <%= form.date_select :start_date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :end_date %>
    <%= form.date_select :end_date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.submit 'Save', class: 'btn btn-info' %>
    <%= link_to 'Back', :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit project</h1>
<%= render 'form' %>

app/views/projects/index.html.erb
<div class="container">
  <h1>Projects</h1>
  <% if user_signed_in? %>
    <%= link_to 'New project', new_project_path, class: 'btn btn-outline-primary pull-xs-right' %>
  <% end %>
  <section id="projects">
    <table class="table table-bordered table-striped">
      <thead>
      <tr>
        <td>Name</td>
        <td>Summary</td>
        <td>Start date</td>
        <td>End date</td>
      </tr>
      </thead>
      <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td><%= link_to project.name, project_path(project) %></td>
          <td><%= project.summary %></td>
          <td><%= project.start_date.to_date.strftime("%d %B %Y") %></td>
          <td><%= project.end_date.to_date.strftime("%d %B %Y") %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </section>
</div>

app/views/projects/new.html.erb
<h1>New project</h1>
<%= render 'form' %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
<% if user_signed_in? %>
  <%= link_to 'Edit', edit_project_path(@project) %>
  |
  <%= link_to 'Delete', project_path(@project), method: :delete, data: {confirm: 'Are you sure?'} %>
<% end %>


    <p>Description: <%= @project.summary %></p>
    <p>Start date: <%= @project.start_date.to_date.strftime("%d %B %Y") %></p>
    <p>End date: <%= @project.end_date.to_date.strftime("%d %B %Y") %></p>

  <h1>Project tasks</h1>


    <table class="table table-bordered table-striped">
      <thead>
      <tr>
        <td>Title</td>
        <td>Description</td>
        <td>Status</td>
      </tr>
      </thead>
      <tbody>
      <% @project.tasks.each do |task| %>
        <tr>
          <td><%= link_to task.title, task_path(task) %></td>
          <td><%= task.description %></td>
          <td><%= task.status %></td>
        </tr>
      <% end %>
      </tbody>
    </table>

app/views/tasks/_form.html.erb
<% if @task.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
  </div>
  <ul>
    <% @task.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_for @task do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :status %>
    <%= form.select(:status, ['new', 'in progress', 'done']) %>
  </div>

  <div class="form-group">
    <%= form.label :project_id %>
    <%= form.collection_select :project_id, Project.order(:name), :id, :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :user_id %>
    <%= form.collection_select :user_id, User.order(:last_name), :id, :last_name %>
  </div>

  <div class="form-group">
    <%= form.submit 'Save', class: 'btn btn-info' %>
    <%= link_to 'Back', :back, class: 'btn btn-outline-secondary' %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<div class="container">
  <h1>Tasks</h1>
  <% if user_signed_in? %>
  <%= link_to 'New task', new_task_path, class: 'btn btn-outline-primary pull-xs-right' %>
    <% end %>
  <section id="projects">
    <table class="table table-bordered table-striped">
      <thead>
      <tr>
        <td>Title</td>
        <td>Description</td>
        <td>Status</td>
        <td>Assigned to</td>
      </tr>
      </thead>
      <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= link_to task.title, task_path(task) %></td>
          <td><%= task.description %></td>
          <td><%= task.status %></td>
          <td>
            <% if task.user.present? %>
              <%= task.user.first_name %>
              <%= task.user.last_name %>
            <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </section>
</div>

app/views/tasks/new.html.erb
<h1>New task</h1>
<%= render 'form' %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<% if user_signed_in? %>
<%= link_to 'Edit', edit_task_path(@task) %>
|
<%= link_to 'Delete', task_path(@task), method: :delete, data: {confirm: 'Are you sure?'} %>
<% end %>
<div>
  <label>Project:</label>
  <% if @task.project.present? %>
    <%= link_to @task.project.name, @task.project %>
</div>
<% end %>

<div>
  <label>Description:</label>
  <%= @task.description %>
</div>
<div>
  <label>Status:</label>
  <%= @task.status %>
</div>
<div>
  <label>Assigned to:</label>
  <%= @task.user.first_name %>
  <%= @task.user.last_name %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>